In [6]:
'''
@Author: Sudhanshu Kumar
@Date: 10 - 10 - 2024
@Last Modified by: Sudhanshu Kumar
@Last Modified time: 10 - 10 - 2024
@Title: Python program to put border as 0

'''

'\n@Author: Sudhanshu Kumar\n@Date: 10 - 10 - 2024\n@Last Modified by: Sudhanshu Kumar\n@Last Modified time: 10 - 10 - 2024\n@Title: Python program to put border as 0\n\n'

In [7]:
import numpy as np 
import logger

log = logger.logger_init('Border_1_Other_0.ipynb')

In [8]:
def create(row,column):
    """
    Description: 
        This function will create a array with border 0 
    Parameters:
        row: number of rows 
        column: number of columns
    Returns:
        final 2-d array
    """

    np_array = np.arange(0,row*column).reshape(row,column)
    for i in range(row):
        for j in range(column):
            if i==0 or i==row-1 or j==0 or j==column-1:
                np_array[i][j] = 0

    return np_array


In [9]:
def main():
    row = int(input("Enter row : "))
    column = int(input("Enter column : "))

    log.info(f"{create(row,column)}")


In [10]:
if __name__=="__main__":
    main()

2024-10-10 14:57:19,860:INFO:Border_1_Other_0.ipynb:[[ 0  0  0  0  0]
 [ 0  6  7  8  0]
 [ 0 11 12 13  0]
 [ 0 16 17 18  0]
 [ 0  0  0  0  0]]
2024-10-10 14:57:19,860:INFO:Border_1_Other_0.ipynb:[[ 0  0  0  0  0]
 [ 0  6  7  8  0]
 [ 0 11 12 13  0]
 [ 0 16 17 18  0]
 [ 0  0  0  0  0]]
